#Install Nginx

- name: Intall Nginx and run
  hosts: Web
  Tasks:
  - name: Install Nginx
    ansible.builtin.package: #heterogeneous module that works for all the distributions
     name: nginx
     state: present 