#Install Nginx

- name: Intall Nginx and run
  hosts: Web
  tasks:
   - name: Install Nginx
     ansible.builtin.package: #heterogeneous module that works for all the distributions
     state: present 