#Variables

- name: Variables to print
  hosts: Web
  become: yes
  vars:
   COURSE: "Devops with AWS"
   Duration: 120
   Trainer: "Shiva Kumar Reddy"
  tasks:
   - name: Print the information from the Variables
     ansible.builtin.debug: 
      msg: "Hi, I am Learnig {{  COURSE  }} through Join Devops, Duration: {{ Duration }} Hours, Trainer: {{ Trainer  }}"
