- name: Ansible loops
  hosts: local
  connection: local
  tasks:
  - name: Print Names
    ansible.builtin.package:
     name: "{{  item }}"
     state: present
    loop: 
     - mysql
     - nginx
     - postfix

