- name: Filters/Functions
  hosts: local
  connection: local
  tasks:
  - name: Print the default value
    ansible.builtin.debug:
     msg: "Hello {{ course | default('AWS') }}"

  - name: Convert to Upper Case
    vars: 
     greeting: "Hello Madhu"
    ansible.builtin.debug:
     msg: "{{ greeting | upper }}"

  - name: Convert to Lower Case
    vars: 
     greeting: "Hello Madhu"
    ansible.builtin.debug:
     msg: "{{ greeting | lower }}"

  - name: Get the Unique values
    vars: 
     numbers: [1,2,3,4,1,4,5,7,3]
    ansible.builtin.debug:
     msg: "{{ numbers | unique }}"

  - name: Get the min and max values
    vars: 
     numbers: [1,2,3,4,1,4,5,7,3]
    ansible.builtin.debug:
     msg: "Min {{ numbers | min }} Max {{ numbers | max }}"